---
title: "10x Genomics scATAC-seq hash arrow file"
author: 
 - Lucas Graybuck
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    self_contained: true
params:
  in_frag: NULL
  in_meta: NULL
  in_key: NULL
  in_well: NULL
  genome: NULL
  refs: NULL
  window_sizes: NULL
  out_dir: NULL
---

<a id="contents"></a>



#### Load libraries:
```{r Load Libraries}
start_time <- Sys.time()

quiet_library <- function(...) {
  suppressPackageStartupMessages(library(...))
}
quiet_library(ATAComb)
quiet_library(H5weaver)
quiet_library(ArchR)
options(stringsAsFactors = FALSE)
```

Declaring start
```{r Declare start}
stm("Starting scATAC-seq Arrow")
```

#### Argument parsing
```{r Parse arguments}
if(is.null(params$in_frag)) {
  stm(paste0("ERROR: No Inputs"))
} else {
  in_frag <- params$in_frag
  in_meta <- params$in_meta
  in_key <- params$in_key
  genome <- params$genome
  out_dir <- params$out_dir
}

  
# Check Genome
if(!genome %in% c("hg38","hg19")) {
  stm(paste0("Genome must be 'hg38' or 'hg19'. Genome provided: ", genome))
  stop()
}


stm(paste0("IN  Fragments dir    : ", in_frag))
stm(paste0("IN  Metadata dir     : ", in_meta))
stm(paste0("IN  SampleSheet      : ", in_key))
stm(paste0("IN  Genome           : ", genome))
stm(paste0("OUT Directory        : ", out_dir))
```

#### Input Parameters
```{r Print Arguments}
print(c(
  paste0("IN  Fragments dir    : ", in_frag),
  paste0("IN  Metadata dir     : ", in_meta),
  paste0("IN  SampleSheet      : ", in_key),
  paste0("IN  Genome           : ", genome),
  paste0("OUT Arrow directory  : ", out_dir)
))
```

#### Set ArchR parameters
```{r setup archr}


stm("Setting ArchR parameters")
set.seed(3030)

available_cores <- parallel::detectCores()
stm(paste0("Using ",available_cores, " threads"))

addArchRThreads(available_cores, force = TRUE)
addArchRGenome(genome)
```

#### Check Input Files
```{r Check Inputs}
 if(!dir.exists(in_frag)) {
   stm(paste0("ERROR: Cannot find IN preprocessed dir:", in_frag))
   stop()
 }
 if(!dir.exists(in_meta)) {
   stm(paste0("ERROR: Cannot find Metadata directory :", in_meta))
   stop()
 } 
 if(!file.exists(in_key)) {
   stm(paste0("ERROR: Cannot find IN SampleSheet file:", in_key))
   stop()
 }

```


#### Create out directory if missing
```{r Create Out Dir}
if(!dir.exists(out_dir)) {
  stm(paste0("Creating Output Directory: ",out_dir))
  dir.create(out_dir, 
             recursive = TRUE)
}
```


[Return to Contents](#contents)




#### Load SampleSheet
```{r Load SampleSheet}
stm(paste0("Reading SampleSheet from ", in_key))

samplesheet <- read.csv(in_key)

in_sample <- as.character(samplesheet$SampleID)

in_batch=samplesheet$BatchID[1]
in_pool=samplesheet$PoolID[1]
out_prefix <- file.path(out_dir, paste0(in_batch, "_", in_sample, "_", in_pool, "_"))
names(out_prefix)=in_sample

```

[Return to Contents](#contents)

<a id="archr"></a>

### ArchR QC analysis

#### Create Arrow file
```{r}
stm(paste0("ArchR: Building ArrowFile from ",in_frag))

for (samp in in_sample){
  # metadata
  metadata_file=paste0(in_meta,"/",in_batch,"_",samp,"_",in_pool,"_filtered_metadata.csv.gz")
  filtered_meta = fread(metadata_file)
  valid_barcodes <- list(bcs = filtered_meta$original_barcodes)
  names(valid_barcodes) <- samp
  valid_barcodes <- SimpleList(valid_barcodes)

   
  fragment_file=paste0(in_frag,"/",in_batch,"_",samp,"_",in_pool,"_fragments.tsv.gz")
  

  ArrowFile <- createArrowFiles(inputFiles = fragment_file,
                               sampleNames = samp,
                               validBarcodes = valid_barcodes,
                               minFrags = 500,
                               minTSS = 0,
                               maxFrags = 1e6,
                               force = TRUE)

stm(paste0("ArchR: ArrowFile generated at ", ArrowFile))

n_total <- nrow(filtered_meta)
stm(paste0("ArchR: Total barcodes = ", n_total))

out_arrow <- paste0(out_prefix[samp], "archr.arrow")
stm(paste0("Saving .arrow to ", out_arrow))
file.copy(ArrowFile, out_arrow)

}
```




<a id="session_info"></a>

## Session Information

```{r Session Info}
sessionInfo()
```

Total time elapsed
```{r Show Time}
end_time <- Sys.time()
diff_time <- end_time - start_time
time_message <- paste0("Elapsed Time: ", 
                       round(diff_time, 3),
                       " ", units(diff_time))
print(time_message)
stm(time_message)
stm("10x ATAC Hash ArrowFiles complete.")
```

[Return to Contents](#contents)
