#' Compute a frequency and metrics table for a 10x ATAC-seq experiment
#'
#' @param fragments_tsv path to an outs/fragments.tsv.gz file generated by cellranger-atac
#' @param keep_barcodes a character vector specifying which barcodes to retain for analysis
#' @param summary_csv path to an outs/summary.csv file generated by cellranger-atac
#'
#' @return a list with two objects: freq_mat, a 2-column matrix containing the histogram of fragment counts; metrics, a data.frame with totals for reads, umis, and counts.
#' @export
tenx_atac_freq <- function(fragments_tsv,
                           keep_barcodes = NULL,
                           summary_csv) {

  cat("reading metrics")

  metrics_table <- read.csv(summary_csv,
                            stringsAsFactors = FALSE)

  cat("reading counts\n")

  fragments <- vroom::vroom(fragments_tsv,
                            delim = "\t",
                            col_names = c("chr","start","end","barcode","n_reads"),
                            col_types = vroom::cols_only(barcode = vroom::col_character(),
                                                         n_reads = vroom::col_integer()))

  cat("computing frequencies\n")

  if(!is.null(keep_barcodes)) {
    fragments <- fragments[fragments$barcode %in% keep_barcodes,]
  }

  freqs <- table(fragments$n_reads)

  freq_mat <- matrix(c(as.numeric(names(freqs)),
                       freqs),
                     ncol = 2)

  total_counts <- sum(freq_mat[,1] * freq_mat[,2])
  total_umis <- sum(freq_mat[,2])
  total_reads <- as.numeric(metrics_table$num_fragments)

  cat("assembling results\n")

  total_metrics <- data.frame(total_reads = total_reads,
                              total_umis = total_umis,
                              total_counts = total_counts)

  list(freq_mat = freq_mat,
       total_metrics = total_metrics,
       tenx_metrics = metrics_table)
}
